id = "emmet"
name = "Emmet"
description = "Emmet support"
version = "0.0.12"
schema_version = 1
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
repository = "https://github.com/zed-extensions/emmet"

[language_servers.emmet-language-server]
name = "Emmet Language Server"
languages = [
    "Angular",
    "Blade",
    "CSS",
    "Django",
    "ERB",
    "Elixir",
    "HEEx",
    "HTML",
    "HTML+ERB",
    "JavaScript",
    "Jinja2",
    "LESS",
    "Liquid",
    "Nunjucks",
    "PHP",
    "SCSS",
    "Statamic Antlers",
    "TSX",
    "Vue.js",
]

[language_servers.emmet-language-server.language_ids]
"Angular" = "angular"
"Blade" = "blade"
"CSS" = "css"
"Django" = "html"
"ERB" = "eruby"
"Elixir" = "elixir"
"HEEx" = "heex"
"HTML" = "html"
"HTML+ERB" = "eruby"
"JavaScript" = "javascriptreact"
"Jinja2" = "html"
"LESS" = "less"
"Liquid" = "html"
"Nunjucks" = "html"
"PHP" = "php"
"SCSS" = "scss"
"Statamic Antlers" = "html"
"TSX" = "typescriptreact"
"Vue.js" = "vue"
